---
title: "Debugging and condition handling"
date: 2019-03-01

type: docs
toc: true
draft: false
aliases: ["/program_condition_handle.html"]
categories: ["programming"]

menu:
  notes:
    parent: Programming elements
    weight: 7
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE)
```

```{r packages, cache = FALSE, message = FALSE}
library(tidyverse)
set.seed(1234)

theme_set(theme_minimal())
```

{{% callout note %}}

Run the code below in your console to download this exercise as a set of R scripts.

```r
usethis::use_course("uc-cfss/debugging-and-defensive-programming")
```

{{% /callout %}}

**Conditions** are a method for communicating to the user when something unanticipated has occurred. Helpfully, many package authors will build these into their functions to explicitly communicate with users when they attempt to use the function improperly. In fact, when you write your own functions you too can use conditions to alert users when something has gone wrong. There are three levels of conditions in R, which each lead to different outcomes.

## Types of conditions

## Fatal errors

**Fatal errors** are raised by `stop()` and force all execution to terminate. Typically errors are used to abort code or a function when it is impossible for the function to continue.

```{r error, error = TRUE}
addition <- function(x, y){
  if(!is.numeric(c(x, y))) stop("One of your inputs is not a number.")
  
  x + y
}

addition(3, "abc")
```

## Warnings

**Warnings** are generated by `warning()` and used to display potential problems. The function or code will continue to process, but the user will be notified that something undesirable has occurred. For example, the [**logit transformation**](https://en.wikipedia.org/wiki/Logit) converts a probability $p$ to the **log-odds**, or the logarithm of the odds. We can write a function to do this for us, but because probability values must be between 0 and 1, it will fail when $x$ is outside of the range $[0,1]$.

```{r logit, error = TRUE}
logit <- function(x){
  log(x / (1 - x))
}

logit(-1)
```

The result of `logit(-1)` is `NaN`.^[`NaN` is distinct from `NA`. `NA` refers to a missing value and can take on different forms depending on the vector type (e.g. `NA_integer_`, `NA_real_`, `NA_complex_` and `NA_character_`). `NaN` stands for ["Not a Number"](https://en.wikipedia.org/wiki/NaN) and represents undefined or unrepresentable values. As in our example, $\frac{-1}{1 - {-1}} = \frac{-1}{0}$ which is indeterminate.] But the message produced is rather opaque. We could add a custom error message to stop the whole function:

```{r logit_error, error = TRUE}
logit <- function(x){
 if(x < 0 | x > 1) stop('x not between 0 and 1')
 log(x / (1 - x))
}

logit(-1)
```

But what if instead we wanted to produce an `NA` value in these situations, and just warn the user what happened (but less cryptically)? We could revise this yet again to produce a warning message:

```{r logit_warning}
logit <- function(x){
  x <- if_else(x < 0 | x > 1, NA_real_, x)
  if(is.na(x)) warning('x not between 0 and 1')
  log(x / (1 - x))
}

logit(-1)
```

## Messages

Messages are generated by `message()` and are used to give informative output to the user. It doesn't mean anything even went wrong, just that there is some information that might prove useful. You've seen these before in `ggplot()` when generating smoothing lines.

```{r message_ggplot}
ggplot(diamonds, aes(carat, price)) +
  geom_point() +
  geom_smooth()
```

Did you see the message?

```
## `geom_smooth()` using method = 'gam'
```

This tells us that `geom_smooth()` generated the line using the `gam()` method.^[Run `?geom_smooth` to see the different methods that can be used.] Nothing went wrong, there was no unexpected behavior, that is just the default smoothing method for a dataset of this size. But it is helpful because what if you wanted to use a linear smoothing function instead? Now you know it was not the default method, and if you want to use it you need to explicitly set it.

```{r message_ggplot_override}
ggplot(diamonds, aes(carat, price)) +
  geom_point() +
  geom_smooth(method = "lm")
```

The nice thing about messages is that they can be suppressed using the `suppressMessages()` function. This way if your function produces dozens or hundreds of messages, you can block them from being printed. A nice feature if you are knitting an R Markdown document. If you were to include messages simply by using the `print()` function, they could not be ignored.

```{r message_print}
demo_message <- function() message("This is a message")
demo_message()
suppressMessages(demo_message())  # no output

demo_print <- function() print("This is a message")
demo_print()
suppressMessages(demo_print())  # still output
```

## Exercise: build a function with conditions

This is a basic function that calculates the square root of the sum of two numbers.

```{r sqrt}
sqrt_sum <- function(x, y){
  sqrt(sum(x, y))
}

sqrt_sum(3, 6)
```

However, look at what happens when the sum of the numbers is negative.

```{r}
sqrt_sum(3, -6)
```

We get a cryptic error message. What happened? **You cannot take the square root of a negative number.** Let's rewrite the function to be explicit with this.

1. Rewrite `sqrt_sum()` to produce a fatal error any time the sum of the two numbers is negative.

    {{< spoiler text="Click for the solution" >}}

```{r exercise_error, error = TRUE}
sqrt_sum <- function(x, y){
  if(sum(x, y) < 0) stop("The sum of these numbers is negative.")
  sqrt(x + y)
}

sqrt_sum(3, -6)
```

    {{< /spoiler >}}

1. Rewrite `sqrt_sum()` to return a missing value (`NA`) any time the sum of the two numbers is negative and produce a warning message explaining why this happened.

    {{< spoiler text="Click for the solution" >}}

```{r exercise_warning, error = TRUE}
sqrt_sum <- function(x, y) {
  if(sum(x, y) < 0) {
    warning("The sum of these numbers is negative.")
    return(NA)
  }
  sqrt(x + y)
}

sqrt_sum(3,-6)
```    

    {{< /spoiler >}}

## Tracking down bugs using `traceback()`

Hadley writes a [detailed breakdown of all the debugging tools available in RStudio](http://adv-r.had.co.nz/Exceptions-Debugging.html#debugging-tools). Here I want to focus on one specific tool, the **traceback**.

## The call stack

The **call stack** is the sequence of calls that lead up to an error. Remember that when you execute a function in R, that function relies on additional functions to complete your task. In order to determine which function generated the bug, we need to "trace back" through the call stack to find the problematic function.

Here's a trivial example from *Advanced R*. Note the sequence of functions:

* `f()` calls `g()`
* `g()` calls `h()`
* `h()` calls `i()`
* `i()` adds together a number and a string, creating an error

```{r callstack, error = TRUE}
f <- function(a) g(a)
g <- function(b) h(b)
h <- function(c) i(c)
i <- function(d) "a" + d
f(10)
```

![Output of `f(10)` in RStudio](/img/traceback-hidden.png)

Clearly the error is not generated by `f()`, yet at first glance all we know is that by executing `f()` we have generated an error. How could we view the call stack to determine the sequence of functions leading up to the error? By using RStudio, you see an option to "Show Traceback". If you click on this option you should see the following:

![Traceback of `f(10)` in RStudio](/img/traceback-shown.png)

Alternatively, run `traceback()` in the console:

```{r traceback, eval = FALSE}
traceback()
```

```
# 4: i(c) at exceptions-example.R#3
# 3: h(b) at exceptions-example.R#2
# 2: g(a) at exceptions-example.R#1
# 1: f(10)
```

We read the call stack from bottom to top. The first call was `f(10)`, which calls `g()`, which calls `h()`, which calls `i()`, which triggers the error. If the code is saved in a file, R will also print the location where the function is saved using the format `filename.R#linenumber`. Now we know the actual error occurred in `i()`, so we would look at the body of this function to try and fix the problem.

## Condition handling

Unexpected errors should be hunted down and destroyed. Well, maybe they just require interactive debugging to figure out what went wrong so you can revise the code to avoid the error. However in other instances you may have **expected errors**, or errors that don't require interactive debugging, but instead just require automatic handling. This commonly occurs when you are fitting many statistical models to data sets, or iterating over a list or the columns of a data frame. In these situations you don't want the entire iteration to fail because of a single element; instead, you want to complete the entire operation and then examine errors after the fact. There are two methods for condition handling I want to demonstrate and practice in this lesson:

* `base::try()` allows you to continue execution even if a fatal error occurs
* `purrr::safely()` is an **adverb** that modifies functions to never throw an error; instead, any output, messages, warnings, and errors are captured as enhanced output.

{{% callout warning %}}

Compiling an RMarkdown document with an error in a code chunk can be difficult. The information you get when knitting the document may be more cryptic than usual. If there is some reason you want to allow a document to continue knitting even after an error is encountered, set the chunk option `error = TRUE`. If an error occurs within that code chunk, `knitr` will ignore it and keep running.

{{% /callout %}}

## Ignore errors with `try()`

`try()` allows a function to continue execution even after a fatal error occurs. Recall that under normal circumstances, a fatal error immediately terminates a function and prevents the function from returning a value:

```{r try_error, error = TRUE}
f1 <- function(x) {
  log(x)
  10
}
f1("x")
```

If we wrap the statement that generates the error in `try()`, the error will be signaled, but execution of the function will continue.

```{r try_error_wrap, error = TRUE}
f2 <- function(x) {
  try(log(x))
  10
}
f2("a")
```

To pass larger blocks of code, wrap them in `{}`:

```r
try({
  a <- 1
  b <- "x"
  a + b
})
```

## Dealing with failure using `safely()`

`try()` is part of base R and like its cousins `tryCatch()` and `withCallingHandlers()` has existed for years now. If you begin to write and develop your own functions on a regular basis you should familiarize yourself with and practice these condition handling methods. However I presume the vast majority of you, at least for the immediate future, will more likely rely on existing functions. When you encounter errors in these situations, you are not going to rewrite functions from packages like `dplyr` or `ggplot2`. Instead, you want a method of dealing with failure that doesn't bring your code to a crashing halt.

![Artwork by @allison_horst](/img/allison_horst_art/purrr_cat.png)

Enter the `safely()` function. This function is an **adverb** in that it takes a function (a verb in `tidyverse` speak) and returns a modified version. The modified version never throws an error, but instead returns a list with two elements:

1. `result` is the original result. If there was an error, then this will be `NULL`.
1. `error` is an error object. If the operation was successful, then this will be `NULL`.

This is quite similar to `try()`, but the result is more predictable. Let's look at a basic function like `sqrt()`:

```{r sqrt_safely}
safe_sqrt <- safely(sqrt)
str(safe_sqrt(9))
str(safe_sqrt("a"))
```

When the function succeeds, the `result` element contains the expected result and `error` is empty (more formally, is `NULL`). When the function fails, the `result` element is `NULL` and the error element contains the error object.

The benefit of `safely()` quickly becomes apparent when used in conjunction with `map()`.

```{r safely_map, error = TRUE}
x <- list("a", 4, 5)

# unsafely square root
y <- x
  map(sqrt)

# safely square root
y <- x %>%
  map(safely(sqrt))
str(y)
```

The beauty is that the result of `map()` and `safely()` is entirely predictable. It will always contain the same number of elements as the original data object (in this case a list), and each element will be another list of two elements: the `result` and the `error`.

However a different structure could be more useful to work with: two lists, one with all the errors and one with all the results. To obtain that, we just use `transpose()`:

```{r transpose}
y <- y %>%
  transpose()
str(y)
```

To extract the values of `x` where `y` is an error:

```{r error_x}
is_ok <- y$error %>%
  map_lgl(is_null)
x[!is_ok]
```

To extract the values of `y` that are ok:

```{r okay_y}
y$result[is_ok] %>%
  flatten_dbl()
```

`safely()` comes from the `purrr` package (hence why it plays so nicely with `map()`). `purrr` also provides two related adverbs for condition handling:

* `possibly()` always returns a result, but the difference is that you specify a default value to return if an error occurs:

    ```{r possibly}
    x %>%
      map_dbl(possibly(sqrt, NA))
    ```

* `quietly()` captures not only errors, but printed output, messages, and warnings as well:

    ```{r quietly}
    x <- list(1, -1)
    x %>%
      map(quietly(sqrt)) %>%
      str()
    ```

## Exercise: handle conditions using `safely()`

1. Write an iterative operation that safely calculates the maximum value for every column in `rcfss::gun_deaths`.

    {{< spoiler text="Click for the solution" >}}
    
```{r gun_deaths_safely}
library(rcfss)

# for loop
output <- vector("list", ncol(gun_deaths))
safe_max <- safely(max) # cannot pass na.rm parameter here

for(i in seq_along(gun_deaths)){
  output[[i]] <- safe_max(gun_deaths[[i]], na.rm = TRUE)
}

str(output)

# map
gun_deaths %>%
  map(safe_max, na.rm = TRUE)
```
    
    {{< /spoiler >}}

1. Perform the same operation as above, but this time replace error messages with a missing value (`NA`).

    {{< spoiler text="Click for the solution" >}}
    
```{r gun_deaths_possibly}
# for loop
output <- vector("list", ncol(gun_deaths))
possible_max <- possibly(max, NA)

for(i in seq_along(gun_deaths)){
  output[[i]] <- possible_max(gun_deaths[[i]], na.rm = TRUE)
}

str(output)

# map
gun_deaths %>%
  map(possible_max, na.rm = TRUE)

## same thing without predefining the adverb
gun_deaths %>%
  map(possibly(max, NA), na.rm = TRUE)
```
    
    {{< /spoiler >}}

## Acknowledgments

* Logit example drawn from [How to create error messages in R](http://www.dummies.com/programming/r/how-to-generate-your-own-error-messages-in-r/)
* Artwork by [@allison_horst](https://github.com/allisonhorst/stats-illustrations)

## Session Info

```{r child = here::here("R", "_session-info.Rmd")}
```
